# -*- coding: utf-8 -*-
# vim: tabstop=4 shiftwidth=4 softtabstop=4
#
# oq-qgis-server
# Copyright (C) 2018-2019 GEM Foundation
#
# oq-qgis-server is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# oq-qgis-server is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: '2'
services:
  nginx:
    image: "docker.io/nginx"
    volumes:
     - ./conf/nginx-fcgi-sample.conf:/etc/nginx/nginx.conf
    ports:
     - "127.0.0.1:8010:80"
    networks:
     - qgis-server-net
    restart: always
    depends_on:
     - qgis-server
  qgis-server:
    image: "docker.io/qgis/qgis-server:stable"
    environment:
      # Do not run the embedded copy of nginx
      SKIP_NGINX: "true"
      # Improve rendering performance
      QGIS_SERVER_PARALLEL_RENDERING: "true"
      QGIS_SERVER_MAX_THREADS: 4
      # Limit the maximum size returned by a GetMap
      QGIS_SERVER_WMS_MAX_HEIGHT: 5000
      QGIS_SERVER_WMS_MAX_WIDTH: 5000
    networks:
     - qgis-server-net
    volumes:
     # Data should be mount RO when working
     # with GeoPackages and more than one QGIS container
     - ./test/data:/io/data:ro
     - ./plugins:/io/plugins
     - ./fonts:/usr/share/fonts
     - ./svg:/var/lib/qgis/.local/share/QGIS/QGIS3/profiles/default/svg
     # - ./conf/pg_service.conf:/etc/postgresql-common/pg_service.conf:ro
    restart: always

networks:
  qgis-server-net:
